# Generated by Django 5.1.7 on 2025-03-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(default='por definir', max_length=250),
            preserve_default=False,
        ),
    ]
